### ISSUE TITLE
Q: Sensirion SPS30 with LoPy4 ?

### ISSUE THREAD

**Issue by justb4** [teusH/MySense#4]
Great project! Obtained a [Sensirion SPS30 PM sensor ](https://www.antratek.nl/particulate-matter-sensor-sps30) , found no drivers yet, e.g. on https://github.com/Sensirion. 

Question is: are you aware of any people/projects combining SPS30 with LoPy4? I also asked via Sensirion contact page (there is no support forum). 

I have some Python skills and experience in other AQ projects like [SmartEmission](https://data.smartemission.nl/). But before I start such activity I am asking around first. Ideally we collaborate with Sensirion on their GH.

**Comment by teusH** [comment]
Due to the fact that I mainly use github from command line I did not notice the question about SPS30 PM sensor and LoPy-4. See the tree PyCom/lib in MySense. There you will find a fully supported driver written in Python for the SPS30 PM sensor. The driver is operational and is used in about 5 kits already. The driver has been tested under python2 and 3 on Raspberry Pi as well LoPy-4. Give feedback if there are improvements.

**Comment by justb4** [comment]
Ok, thanks @teusH !
